-- MySQL Script generated by MySQL Workbench
-- vie 06 abr 2018 19:57:23 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spring-bd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `spring-bd` ;

-- -----------------------------------------------------
-- Schema spring-bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spring-bd` DEFAULT CHARACTER SET utf8 ;
USE `spring-bd` ;

-- -----------------------------------------------------
-- Table `spring-bd`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spring-bd`.`Admin` ;

CREATE TABLE IF NOT EXISTS `spring-bd`.`Admin` (
  `idAd` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NULL,
  `cargo` VARCHAR(45) NULL,
  `fechaCreacion` DATETIME NULL,
  PRIMARY KEY (`idAd`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spring-bd`.`Direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spring-bd`.`Direccion` ;

CREATE TABLE IF NOT EXISTS `spring-bd`.`Direccion` (
  `idDir` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NULL,
  `cp` VARCHAR(45) NULL,
  `idAd` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDir`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

